(()=>{
'use strict';
const PILOT_LESSON_NUMBER=1;
const q=id=>document.getElementById(id);
const state={lessonId:null,quiz:null,index:0,score:0,answered:false,coachTurns:0,history:[],started:false};
const copy={
 pt:{title:'Conversa com o Coach',loading:'Preparando sua conversa…',next:'Próxima pergunta',finish:'Continuar a conversa',coachTitle:'Conversa com o Coach',coachIntro:'Vamos conversar sobre o que você aprendeu nesta aula.',send:'Enviar',placeholder:'Escreva sua resposta…',done:'Conversa concluída ✓',retry:'Tentar novamente',error:'Não foi possível carregar a conversa agora.',score:'Resultado'},
 en:{title:'Coach Conversation',loading:'Preparing your conversation…',next:'Next question',finish:'Continue conversation',coachTitle:'Coach Conversation',coachIntro:'Let’s talk about what you learned in this lesson.',send:'Send',placeholder:'Write your answer…',done:'Conversation completed ✓',retry:'Try again',error:'The Coach Conversation is not available right now.',score:'Score'},
 es:{title:'Conversación con el Coach',loading:'Preparando tu conversación…',next:'Siguiente pregunta',finish:'Continuar conversación',coachTitle:'Conversación con el Coach',coachIntro:'Conversemos sobre lo que aprendiste en esta clase.',send:'Enviar',placeholder:'Escribe tu respuesta…',done:'Conversación completada ✓',retry:'Intentar de nuevo',error:'La conversación con el Coach no está disponible en este momento.',score:'Resultado'}};
const c=k=>copy[(typeof currentLang!=='undefined'&&copy[currentLang])?currentLang:'pt'][k]||k;
function injectStyles(){if(q('abbaCoachStyles'))return;const s=document.createElement('style');s.id='abbaCoachStyles';s.textContent=`
.abba-coach{margin:24px 0;padding:24px;border:1px solid #e4e1dc;border-radius:18px;background:#fff}.abba-coach-head{display:flex;gap:14px;align-items:center;margin-bottom:20px}.abba-coach-icon{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;background:#111;color:#fff;font-weight:700}.abba-coach h2{margin:0;font-size:1.45rem}.abba-coach-status{font-size:.92rem;color:#6b625b}.abba-coach-options{display:grid;gap:10px;margin:18px 0}.abba-coach-option{padding:14px;text-align:left;border:1px solid #d8d3cd;border-radius:12px;background:#fff;cursor:pointer}.abba-coach-option:hover{border-color:#777}.abba-coach-option.correct{border-color:#2f7d4a;background:#f0faf3}.abba-coach-option.wrong{border-color:#b7473b;background:#fff3f1}.abba-coach-option:disabled{cursor:default;color:inherit}.abba-coach-feedback{padding:12px 14px;border-radius:12px;background:#f6f4f1;margin:12px 0}.abba-coach-chat{display:grid;gap:12px;margin:16px 0}.abba-coach-msg{padding:12px 14px;border-radius:14px;max-width:88%;white-space:pre-wrap}.abba-coach-msg.ai{background:#f2f0ed}.abba-coach-msg.user{background:#111;color:#fff;margin-left:auto}.abba-coach-compose{display:flex;gap:8px}.abba-coach-compose textarea{flex:1;min-height:70px;border:1px solid #d8d3cd;border-radius:12px;padding:12px;font:inherit;resize:vertical}.abba-coach button.primary{white-space:nowrap}@media(max-width:640px){.abba-coach{padding:17px}.abba-coach-compose{display:grid}.abba-coach-msg{max-width:95%}}
`;document.head.appendChild(s)}
function ensureHost(){injectStyles();let host=q('abbaAiCoach');if(host)return host;host=document.createElement('section');host.id='abbaAiCoach';host.className='abba-coach hidden';const toolbar=document.querySelector('.lesson-toolbar');toolbar?.insertAdjacentElement('afterend',host);return host}
function isPilot(){return currentLesson&&Number(currentLesson.lesson_number)===PILOT_LESSON_NUMBER}
function isUnlocked(){if(!currentLesson)return false;const p=typeof progressFor==='function'?progressFor(currentLesson.id):null;const player=q('muxPlayer');let nearEnd=false;try{nearEnd=player.duration>0&&player.currentTime/player.duration>=.9}catch{}return !!p?.completed||nearEnd}
function reset(){state.lessonId=currentLesson?.id||null;state.quiz=null;state.index=0;state.score=0;state.answered=false;state.coachTurns=0;state.history=[];state.started=false}
function renderGate(){const host=ensureHost();if(!isPilot()){host.classList.add('hidden');return}if(state.lessonId!==currentLesson.id)reset();if(!isUnlocked()){host.classList.add('hidden');return}host.classList.remove('hidden');if(!state.started){state.started=true;startQuiz();}}
async function api(payload){const {data:{session}}=await db.auth.getSession();if(!session)throw new Error('No session');const r=await fetch(`${SUPABASE_URL}/functions/v1/abba-ai-coach`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,'apikey':SUPABASE_KEY},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'AI Coach error');return j}
async function startQuiz(){const host=ensureHost();host.classList.remove('hidden');host.innerHTML=`<div class="abba-coach-head"><div class="abba-coach-icon">AI</div><h2>${c('title')}</h2></div><p class="abba-coach-status">${c('loading')}</p>`;host.scrollIntoView({behavior:'smooth',block:'start'});try{const j=await api({action:'generate_quiz',lesson_id:currentLesson.id,language:currentLang});state.quiz=j.questions||[];state.index=0;state.score=0;renderQuestion()}catch(e){console.error(e);renderError()}}
function renderQuestion(){const host=ensureHost(),item=state.quiz?.[state.index];if(!item){renderQuizResult();return}state.answered=false;host.innerHTML=`<div class="abba-coach-head"><div class="abba-coach-icon">AI</div><div><h2>${c('title')}</h2><div class="abba-coach-status">${state.index+1} / ${state.quiz.length}</div></div></div><h3>${escapeHtml(item.question)}</h3><div id="abbaCoachOptions" class="abba-coach-options"></div><div id="abbaCoachFeedback"></div>`;const opts=q('abbaCoachOptions');item.options.forEach((label,i)=>{const b=document.createElement('button');b.className='abba-coach-option';b.textContent=label;b.onclick=()=>answer(i,b);opts.appendChild(b)})}
function answer(i){if(state.answered)return;state.answered=true;const item=state.quiz[state.index],correct=i===item.correct_index;if(correct)state.score++;document.querySelectorAll('.abba-coach-option').forEach((b,idx)=>{b.disabled=true;if(idx===item.correct_index)b.classList.add('correct');else if(idx===i)b.classList.add('wrong')});const f=q('abbaCoachFeedback');f.className='abba-coach-feedback';f.innerHTML=`<p>${escapeHtml(item.explanation)}</p><button id="abbaCoachNext" class="primary">${state.index===state.quiz.length-1?c('finish'):c('next')}</button>`;q('abbaCoachNext').onclick=()=>{state.index++;renderQuestion()}}
function renderQuizResult(){const host=ensureHost();host.innerHTML=`<div class="abba-coach-head"><div class="abba-coach-icon">AI</div><div><h2>${c('score')}: ${state.score}/${state.quiz.length}</h2><p>${c('coachIntro')}</p></div></div><button id="abbaCoachBeginChat" class="primary">${c('finish')}</button>`;q('abbaCoachBeginChat').onclick=beginCoach}
async function beginCoach(){state.history=[];state.coachTurns=0;await sendCoach('',true)}
async function sendCoach(text,initial=false){const host=ensureHost();if(!initial&&text.trim()){state.history.push({role:'user',content:text.trim()});state.coachTurns++}renderChat(true);try{const j=await api({action:'coach',lesson_id:currentLesson.id,language:currentLang,history:state.history.slice(-8),quiz_score:state.score,quiz_total:state.quiz.length,initial});state.history.push({role:'assistant',content:j.message});if(j.completed||state.coachTurns>=3)renderCompleted();else renderChat(false)}catch(e){console.error(e);renderError()}}
function renderChat(loading=false){const host=ensureHost();host.innerHTML=`<div class="abba-coach-head"><div class="abba-coach-icon">AI</div><div><h2>${c('coachTitle')}</h2><p>${c('coachIntro')}</p></div></div><div id="abbaCoachChat" class="abba-coach-chat"></div>${loading?`<p class="abba-coach-status">${c('loading')}</p>`:`<div class="abba-coach-compose"><textarea id="abbaCoachInput" maxlength="1200" placeholder="${c('placeholder')}"></textarea><button id="abbaCoachSend" class="primary">${c('send')}</button></div>`}`;const chat=q('abbaCoachChat');state.history.forEach(m=>{const d=document.createElement('div');d.className=`abba-coach-msg ${m.role==='assistant'?'ai':'user'}`;d.textContent=m.content;chat.appendChild(d)});if(!loading){q('abbaCoachSend').onclick=()=>{const v=q('abbaCoachInput').value;if(v.trim())sendCoach(v,false)}}}
function renderCompleted(){const host=ensureHost();host.innerHTML=`<div class="abba-coach-head"><div class="abba-coach-icon">✓</div><div><h2>${c('done')}</h2><p>${c('score')}: ${state.score}/${state.quiz.length}</p></div></div><div id="abbaCoachChat" class="abba-coach-chat"></div><button id="abbaCoachRetry" class="secondary">${c('retry')}</button>`;const chat=q('abbaCoachChat');state.history.forEach(m=>{const d=document.createElement('div');d.className=`abba-coach-msg ${m.role==='assistant'?'ai':'user'}`;d.textContent=m.content;chat.appendChild(d)});q('abbaCoachRetry').onclick=()=>{reset();renderGate()}}
function renderError(){const host=ensureHost();host.classList.remove('hidden');host.innerHTML=`<div class="abba-coach-head"><div class="abba-coach-icon">AI</div><div><h2>${c('title')}</h2><p>${c('error')}</p></div></div><button id="abbaCoachRetry" class="secondary">${c('retry')}</button>`;q('abbaCoachRetry').onclick=()=>{state.started=false;renderGate()}}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
const player=q('muxPlayer');player?.addEventListener('ended',renderGate);player?.addEventListener('timeupdate',()=>{if(isPilot()&&isUnlocked()&&!state.started)renderGate()});
const lessonTitle=q('lessonTitle');if(lessonTitle){new MutationObserver(()=>setTimeout(renderGate,50)).observe(lessonTitle,{childList:true,characterData:true,subtree:true})}
setTimeout(renderGate,1200);
})();
