const SUPABASE_URL='https://yecywtxbuhfukergbwfc.supabase.co';
const SUPABASE_KEY='sb_publishable_jFIuvZYIs1b-6IjqCnDPDw_BDivhFKs';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentUser=null,currentCourse=null,lessons=[],progressRows=[],currentLesson=null,lastSavedPosition=0;
const $=id=>document.getElementById(id);
function show(id,yes=true){$(id).classList.toggle('hidden',!yes)}
function setStatus(msg,bad=false){$('authStatus').textContent=msg;$('authStatus').style.color=bad?'#b42318':'#12805c'}
function progressFor(id){return progressRows.find(x=>x.lesson_id===id)}
function pct(){if(!lessons.length)return 0;return Math.round(progressRows.filter(x=>x.completed).length/lessons.length*100)}
function renderProgress(){const done=progressRows.filter(x=>x.completed).length,p=pct();$('progressLabel').textContent=p+'%';$('progressCount').textContent=`${done} of ${lessons.length||currentCourse?.total_lessons||48} complete`;$('progressBar').style.width=p+'%'}
function moduleNumber(lesson){return Math.ceil(lesson.lesson_number/4)}
function getNextLesson(){return lessons.find(l=>!progressFor(l.id)?.completed)||lessons[lessons.length-1]||null}
function getResumeLesson(){const inProgress=lessons.find(l=>{const p=progressFor(l.id);return p&&!p.completed&&(p.last_position_seconds||0)>15});return inProgress||getNextLesson()}
function renderDashboard(){show('learningDashboard',lessons.length>0);if(!lessons.length)return;const resume=getResumeLesson(),next=getNextLesson();$('continueTitle').textContent=resume?resume.title:'Course completed';const rp=resume?progressFor(resume.id):null;$('continueMeta').textContent=resume?(rp?.last_position_seconds>15?`Resume Lesson ${resume.lesson_number}`:`Start Lesson ${resume.lesson_number}`):'You completed all available lessons.';$('continueBtn').disabled=!resume;$('continueBtn').textContent=resume?(rp?.last_position_seconds>15?'Resume Lesson':'Continue Learning'):'Completed ✓';$('continueBtn').onclick=()=>resume&&openLessonById(resume.id,true);$('upNextTitle').textContent=next?next.title:'All caught up';$('upNextMeta').textContent=next?`Lesson ${next.lesson_number}${next.duration_minutes?' · '+next.duration_minutes+' min':''}`:'You completed all available lessons.';renderModules()}
function renderModules(){const host=$('moduleGrid');host.innerHTML='';const groups=new Map();lessons.forEach(l=>{const m=moduleNumber(l);if(!groups.has(m))groups.set(m,[]);groups.get(m).push(l)});let completedModules=0;for(const [m,items] of groups){const done=items.filter(l=>progressFor(l.id)?.completed).length,p=Math.round(done/items.length*100);if(p===100)completedModules++;const b=document.createElement('button');b.className='module-card';b.innerHTML=`<div class="module-top"><div><small>Module ${m}</small><br><strong>Lessons ${items[0].lesson_number}–${items[items.length-1].lesson_number}</strong></div><span class="module-pct">${p}%</span></div><small>${done} of ${items.length} completed</small><div class="mini-bar"><i style="width:${p}%"></i></div>`;b.onclick=()=>{const target=items.find(l=>!progressFor(l.id)?.completed)||items[0];openLessonById(target.id,true)};host.appendChild(b)}$('moduleSummary').textContent=`${completedModules} of ${groups.size} modules completed`}
function renderLessons(){const host=$('lessonList');host.innerHTML='';$('lessonTotal').textContent=`${lessons.length} available`;lessons.forEach(l=>{const p=progressFor(l.id),b=document.createElement('button');b.className='lesson-btn'+(p?.completed?' done':'');b.dataset.lessonId=l.id;b.innerHTML=`<span class="num">${p?.completed?'✓':l.lesson_number}</span><span><strong>${l.title}</strong><small>${p?.completed?'Completed':(p?.last_position_seconds>15?'In progress':(l.duration_minutes?l.duration_minutes+' min':'Lesson '+l.lesson_number))}</small></span><span class="check">${p?.completed?'Complete':''}</span>`;b.onclick=()=>openLesson(l,b,true);host.appendChild(b)})}
function openLessonById(id,scroll=false){const l=lessons.find(x=>x.id===id),b=document.querySelector(`.lesson-btn[data-lesson-id="${id}"]`);if(l&&b)openLesson(l,b,scroll)}
function openLesson(l,b,scroll=false){currentLesson=l;document.querySelectorAll('.lesson-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');show('lessonEmpty',false);show('lessonContent',true);$('lessonNumber').textContent='Lesson '+l.lesson_number;$('lessonDuration').textContent=l.duration_minutes?l.duration_minutes+' minutes':'';$('lessonTitle').textContent=l.title;$('lessonDescription').textContent=l.description||'';const player=$('muxPlayer');if(l.mux_playback_id){player.setAttribute('playback-id',l.mux_playback_id);show('videoWrap',true);show('videoPending',false);const p=progressFor(l.id);setTimeout(()=>{if(p?.last_position_seconds>15&&!p.completed){try{player.currentTime=p.last_position_seconds}catch{}}},700)}else{player.removeAttribute('playback-id');show('videoWrap',false);show('videoPending',true)}const p=progressFor(l.id);$('completeBtn').textContent=p?.completed?'Completed ✓':'Mark lesson complete';$('completeBtn').disabled=!!p?.completed;$('completeBtn').onclick=()=>markComplete(l.id);const idx=lessons.indexOf(l),next=lessons[idx+1];show('nextBtn',!!next);if(next)$('nextBtn').onclick=()=>openLessonById(next.id,true);if(scroll)$('courseArea').scrollIntoView({behavior:'smooth',block:'start'})}
async function markComplete(lessonId){const payload={user_id:currentUser.id,lesson_id:lessonId,completed:true,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {error}=await db.from('abba_lesson_progress').upsert(payload,{onConflict:'user_id,lesson_id'});if(error){alert(error.message);return}await loadProgress();renderLessons();renderProgress();renderDashboard();openLessonById(lessonId,false)}
async function savePosition(force=false){if(!currentUser||!currentLesson)return;const player=$('muxPlayer');let seconds=0;try{seconds=Math.floor(player.currentTime||0)}catch{return}if(seconds<1)return;if(!force&&Math.abs(seconds-lastSavedPosition)<15)return;lastSavedPosition=seconds;const existing=progressFor(currentLesson.id);const payload={user_id:currentUser.id,lesson_id:currentLesson.id,completed:!!existing?.completed,watched_seconds:Math.max(existing?.watched_seconds||0,seconds),last_position_seconds:seconds,updated_at:new Date().toISOString()};await db.from('abba_lesson_progress').upsert(payload,{onConflict:'user_id,lesson_id'});const local=progressFor(currentLesson.id);if(local){local.last_position_seconds=seconds;local.watched_seconds=payload.watched_seconds}else progressRows.push({...payload});renderDashboard()}
async function loadProgress(){const ids=lessons.map(x=>x.id);if(!ids.length){progressRows=[];return}const {data,error}=await db.from('abba_lesson_progress').select('*').in('lesson_id',ids);if(error)throw error;progressRows=data||[]}
async function loadPortal(){show('authView',false);show('portalView',true);show('signOutBtn',true);const {data:courseData,error:courseErr}=await db.from('abba_courses').select('*').eq('slug','annual-program').single();if(courseErr){$('courseTitle').textContent='ABBA Academy';$('courseDescription').textContent='Course unavailable.';return}currentCourse=courseData;$('courseTitle').textContent=currentCourse.title;$('courseDescription').textContent=currentCourse.description||'';const {data:enrollment}=await db.from('abba_enrollments').select('*').eq('course_id',currentCourse.id).eq('user_id',currentUser.id).eq('status','active').maybeSingle();if(!enrollment){show('noEnrollment',true);show('courseArea',false);show('learningDashboard',false);renderProgress();return}show('noEnrollment',false);show('courseArea',true);const {data:lessonData,error:lessonErr}=await db.from('abba_lessons').select('*').eq('course_id',currentCourse.id).eq('is_published',true).not('mux_playback_id','is',null).order('lesson_number');if(lessonErr){alert(lessonErr.message);return}lessons=lessonData||[];await loadProgress();renderLessons();renderProgress();renderDashboard();const resume=getResumeLesson();if(resume)openLessonById(resume.id,false)}
$('authForm').addEventListener('submit',async e=>{e.preventDefault();setStatus('Signing in...');const email=$('email').value.trim(),password=$('password').value;if(!email||!password){setStatus('Enter your email and password.',true);return}const {data,error}=await db.auth.signInWithPassword({email,password});if(error){setStatus(error.message,true);return}currentUser=data.user;setStatus('');await loadPortal()});
$('signUpBtn').onclick=async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<8){setStatus('Enter an email and a password with at least 8 characters.',true);return}setStatus('Creating account...');const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:'https://alineramiro.com/academy.html'}});if(error){setStatus(error.message,true);return}if(data.session){currentUser=data.user;setStatus('');await loadPortal()}else setStatus('Account created. Check your email to confirm, then sign in.')};
$('forgotBtn').onclick=async()=>{const email=$('email').value.trim();if(!email){setStatus('Enter your email first, then tap Forgot password.',true);$('email').focus();return}setStatus('Sending password reset email...');const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:'https://alineramiro.com/academy-reset.html'});if(error){setStatus(error.message,true);return}setStatus('Check your email. We sent you a secure link to reset your password.')};
$('togglePassword').onclick=()=>{const input=$('password'),showing=input.type==='text';input.type=showing?'password':'text';$('togglePassword').textContent=showing?'Show':'Hide';$('togglePassword').setAttribute('aria-label',showing?'Show password':'Hide password')};
$('signOutBtn').onclick=async()=>{await savePosition(true);await db.auth.signOut();location.reload()};
const muxPlayer=$('muxPlayer');muxPlayer.addEventListener('timeupdate',()=>savePosition(false));muxPlayer.addEventListener('pause',()=>savePosition(true));window.addEventListener('pagehide',()=>savePosition(true));
(async()=>{const {data:{session}}=await db.auth.getSession();if(session?.user){currentUser=session.user;await loadPortal()}})();