(()=>{
const subtitleOptions=[['pt','Português'],['en','English'],['es','Español'],['hi','हिन्दी'],['ne','नेपाली'],['ja','日本語'],['zh','中文']];
let captionLang='pt',translationTimer=null,translationBusy=false;
async function session(){try{return (await db.auth.getSession()).data.session}catch{return null}}
function uiLang(){const l=(document.documentElement.lang||'en').toLowerCase();return ['en','pt','es'].includes(l)?l:'en'}
function words(){const l=uiLang();return l==='pt'?{title:'IDIOMA DOS SUBTÍTULOS',label:'Idioma dos subtítulos',help:'Escolha o idioma da transcrição e dos subtítulos das aulas.',saved:'Idioma dos subtítulos salvo ✓',preparing:'Preparando tradução...',ready:'Tradução pronta ✓',failed:'Não foi possível preparar esta tradução agora.'}:l==='es'?{title:'IDIOMA DE SUBTÍTULOS',label:'Idioma de subtítulos',help:'Elige el idioma de la transcripción y los subtítulos de las clases.',saved:'Idioma de subtítulos guardado ✓',preparing:'Preparando traducción...',ready:'Traducción lista ✓',failed:'No se pudo preparar esta traducción ahora.'}:{title:'SUBTITLE LANGUAGE',label:'Subtitle language',help:'Choose the language used for lesson transcripts and subtitles.',saved:'Subtitle language saved ✓',preparing:'Preparing translation...',ready:'Translation ready ✓',failed:'Could not prepare this translation right now.'}}
async function ensureSettings(){const s=await session();const b=document.getElementById('settingsBtn');if(b&&s)b.classList.remove('hidden');if(!s)return;injectSubtitleSetting();}
function injectSubtitleSetting(){if(document.getElementById('captionLanguageSelect')){translateSubtitleLabels();return}const anchor=document.getElementById('languageLabel')?.closest('.settings-section');if(!anchor)return;const sec=document.createElement('section');sec.className='settings-section';sec.id='captionSettingsSection';sec.innerHTML='<div class="settings-kicker" id="captionTitle"></div><label class="settings-select-row"><span id="captionLabel"></span><select id="captionLanguageSelect"></select></label><p class="settings-help" id="captionHelp"></p><p class="settings-help" id="captionStatus"></p>';anchor.insertAdjacentElement('afterend',sec);const sel=document.getElementById('captionLanguageSelect');subtitleOptions.forEach(([v,n])=>{const o=document.createElement('option');o.value=v;o.textContent=n;sel.appendChild(o)});sel.value=captionLang;sel.addEventListener('change',saveCaptionPreference);translateSubtitleLabels()}
function translateSubtitleLabels(){const t=words();const a=document.getElementById('captionTitle'),b=document.getElementById('captionLabel'),c=document.getElementById('captionHelp');if(a)a.textContent=t.title;if(b)b.textContent=t.label;if(c)c.textContent=t.help}
async function loadCaptionPreference(){const s=await session();if(!s)return;const {data}=await db.from('abba_student_settings').select('preferred_caption_language,preferred_language').eq('user_id',s.user.id).maybeSingle();captionLang=subtitleOptions.some(x=>x[0]===data?.preferred_caption_language)?data.preferred_caption_language:(['pt','en','es'].includes(data?.preferred_language)?data.preferred_language:'pt');injectSubtitleSetting();const sel=document.getElementById('captionLanguageSelect');if(sel)sel.value=captionLang;translateCurrentLesson(true)}
async function saveCaptionPreference(e){captionLang=e.target.value;const s=await session();if(s)await db.from('abba_student_settings').upsert({user_id:s.user.id,preferred_caption_language:captionLang,updated_at:new Date().toISOString()},{onConflict:'user_id'});const st=document.getElementById('captionStatus');if(st)st.textContent=words().saved;translateCurrentLesson(true)}
function saveSource(){if(typeof currentLesson==='undefined'||!currentLesson||currentLesson.__source)return;currentLesson.__source={transcript:currentLesson.transcript,transcript_cues:currentLesson.transcript_cues,summary:currentLesson.summary,key_points:currentLesson.key_points}}
function restorePortuguese(){if(typeof currentLesson==='undefined'||!currentLesson)return;saveSource();if(currentLesson.__source){Object.assign(currentLesson,currentLesson.__source);renderLessonResources(currentLesson)}const st=document.getElementById('captionStatus');if(st)st.textContent=''}
async function requestTranslation(){const s=await session();if(!s||typeof currentLesson==='undefined'||!currentLesson)return null;const r=await fetch(`${SUPABASE_URL}/functions/v1/abba-caption-translations`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`,'apikey':SUPABASE_KEY},body:JSON.stringify({lesson_id:currentLesson.id,language:captionLang})});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||'Translation failed');return j}
async function translateCurrentLesson(force=false){clearTimeout(translationTimer);if(typeof currentLesson==='undefined'||!currentLesson)return;if(captionLang==='pt'){restorePortuguese();return}if(translationBusy&&!force)return;translationBusy=true;saveSource();const st=document.getElementById('captionStatus');if(st)st.textContent=words().preparing;try{const j=await requestTranslation();if(j?.status==='ready'){currentLesson.transcript=j.transcript||'';currentLesson.transcript_cues=Array.isArray(j.transcript_cues)?j.transcript_cues:[];currentLesson.summary=j.summary||'';currentLesson.key_points=Array.isArray(j.key_points)?j.key_points:[];renderLessonResources(currentLesson);if(st)st.textContent=words().ready;const p=document.getElementById('muxPlayer');if(p&&currentLesson.mux_playback_id){let pos=0;try{pos=p.currentTime||0}catch{}p.setAttribute('playback-id',currentLesson.mux_playback_id);setTimeout(()=>{try{p.currentTime=pos}catch{}},700)}return}translationTimer=setTimeout(()=>translateCurrentLesson(),4500)}catch(e){console.warn(e);if(st)st.textContent=words().failed}finally{translationBusy=false}}
const interfaceSel=document.getElementById('languageSelect');if(interfaceSel)interfaceSel.addEventListener('change',()=>setTimeout(translateSubtitleLabels,150));
new MutationObserver(()=>{ensureSettings();translateSubtitleLabels();const lv=document.getElementById('lessonView');if(lv&&!lv.classList.contains('hidden'))translateCurrentLesson()}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class','lang']});
setTimeout(ensureSettings,100);setTimeout(loadCaptionPreference,700);setTimeout(ensureSettings,2000);
})();