const SUPABASE_URL='https://yecywtxbuhfukergbwfc.supabase.co';
const SUPABASE_KEY='sb_publishable_jFIuvZYIs1b-6IjqCnDPDw_BDivhFKs';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentUser=null,currentCourse=null,lessons=[],progressRows=[];
const $=id=>document.getElementById(id);
function show(id,yes=true){$(id).classList.toggle('hidden',!yes)}
function setStatus(msg,bad=false){$('authStatus').textContent=msg;$('authStatus').style.color=bad?'#b42318':'#12805c'}
function pct(){if(!lessons.length)return 0;return Math.round(progressRows.filter(x=>x.completed).length/lessons.length*100)}
function renderProgress(){const done=progressRows.filter(x=>x.completed).length,p=pct();$('progressLabel').textContent=p+'%';$('progressCount').textContent=`${done} of ${lessons.length||currentCourse?.total_lessons||48} complete`;$('progressBar').style.width=p+'%'}
function progressFor(id){return progressRows.find(x=>x.lesson_id===id)}
function renderLessons(){const host=$('lessonList');host.innerHTML='';$('lessonTotal').textContent=`${lessons.length} available`;lessons.forEach(l=>{const p=progressFor(l.id),b=document.createElement('button');b.className='lesson-btn'+(p?.completed?' done':'');b.innerHTML=`<span class="num">${p?.completed?'✓':l.lesson_number}</span><span><strong>${l.title}</strong><small>${l.duration_minutes?l.duration_minutes+' min':'Lesson '+l.lesson_number}</small></span><span class="check">${p?.completed?'Complete':''}</span>`;b.onclick=()=>openLesson(l,b);host.appendChild(b)})}
function openLesson(l,b){document.querySelectorAll('.lesson-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');show('lessonEmpty',false);show('lessonContent',true);$('lessonNumber').textContent='Lesson '+l.lesson_number;$('lessonDuration').textContent=l.duration_minutes?l.duration_minutes+' minutes':'';$('lessonTitle').textContent=l.title;$('lessonDescription').textContent=l.description||'';const player=$('muxPlayer');if(l.mux_playback_id){player.setAttribute('playback-id',l.mux_playback_id);show('videoWrap',true);show('videoPending',false)}else{player.removeAttribute('playback-id');show('videoWrap',false);show('videoPending',true)}const p=progressFor(l.id);$('completeBtn').textContent=p?.completed?'Completed ✓':'Mark lesson complete';$('completeBtn').disabled=!!p?.completed;$('completeBtn').onclick=()=>markComplete(l.id)}
async function markComplete(lessonId){const payload={user_id:currentUser.id,lesson_id:lessonId,completed:true,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {error}=await db.from('abba_lesson_progress').upsert(payload,{onConflict:'user_id,lesson_id'});if(error){alert(error.message);return}await loadProgress();renderLessons();renderProgress();const l=lessons.find(x=>x.id===lessonId),idx=lessons.indexOf(l);if(l){const buttons=[...document.querySelectorAll('.lesson-btn')];openLesson(l,buttons[idx])}}
async function loadProgress(){const ids=lessons.map(x=>x.id);if(!ids.length){progressRows=[];return}const {data,error}=await db.from('abba_lesson_progress').select('*').in('lesson_id',ids);if(error)throw error;progressRows=data||[]}
async function loadPortal(){show('authView',false);show('portalView',true);show('signOutBtn',true);const {data:courseData,error:courseErr}=await db.from('abba_courses').select('*').eq('slug','annual-program').single();if(courseErr){$('courseTitle').textContent='ABBA Academy';$('courseDescription').textContent='Course setup in progress.';return}currentCourse=courseData;$('courseTitle').textContent=currentCourse.title;$('courseDescription').textContent=currentCourse.description||'';const {data:enrollment}=await db.from('abba_enrollments').select('*').eq('course_id',currentCourse.id).eq('user_id',currentUser.id).eq('status','active').maybeSingle();if(!enrollment){show('noEnrollment',true);show('courseArea',false);renderProgress();return}show('noEnrollment',false);show('courseArea',true);const {data:lessonData,error:lessonErr}=await db.from('abba_lessons').select('*').eq('course_id',currentCourse.id).eq('is_published',true).not('mux_playback_id','is',null).order('lesson_number');if(lessonErr){alert(lessonErr.message);return}lessons=lessonData||[];await loadProgress();renderLessons();renderProgress()}
$('authForm').addEventListener('submit',async e=>{e.preventDefault();setStatus('Signing in...');const email=$('email').value.trim(),password=$('password').value;if(!email||!password){setStatus('Enter your email and password.',true);return}const {data,error}=await db.auth.signInWithPassword({email,password});if(error){setStatus(error.message,true);return}currentUser=data.user;setStatus('');await loadPortal()});
$('signUpBtn').onclick=async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<8){setStatus('Enter an email and a password with at least 8 characters.',true);return}setStatus('Creating account...');const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:'https://alineramiro.com/academy.html'}});if(error){setStatus(error.message,true);return}if(data.session){currentUser=data.user;setStatus('');await loadPortal()}else setStatus('Account created. Check your email to confirm, then sign in.')};
$('forgotBtn').onclick=async()=>{const email=$('email').value.trim();if(!email){setStatus('Enter your email first, then tap Forgot password.',true);$('email').focus();return}setStatus('Sending password reset email...');const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:'https://alineramiro.com/academy-reset.html'});if(error){setStatus(error.message,true);return}setStatus('Check your email. We sent you a secure link to reset your password.')};
$('togglePassword').onclick=()=>{const input=$('password'),showing=input.type==='text';input.type=showing?'password':'text';$('togglePassword').textContent=showing?'Show':'Hide';$('togglePassword').setAttribute('aria-label',showing?'Show password':'Hide password')};
$('signOutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};
(async()=>{const {data:{session}}=await db.auth.getSession();if(session?.user){currentUser=session.user;await loadPortal()}})();