const SUPABASE_URL='https://yecywtxbuhfukergbwfc.supabase.co';
const SUPABASE_KEY='sb_publishable_jFIuvZYIs1b-6IjqCnDPDw_BDivhFKs';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let session=null,lessons=[],current=null;
const $=id=>document.getElementById(id); const show=(id,yes=true)=>$(id).classList.toggle('hidden',!yes);
async function api(payload){const {data:{session:s}}=await db.auth.getSession(); if(!s)throw new Error('Please sign in again.'); const r=await fetch(`${SUPABASE_URL}/functions/v1/abba-mux-admin`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.access_token}`,'apikey':SUPABASE_KEY},body:JSON.stringify(payload)}); const j=await r.json(); if(!r.ok)throw new Error(j.error||'Request failed'); return j;}
function fmtLocal(v){if(!v)return'';const d=new Date(v);const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function render(){const host=$('lessons');host.innerHTML='';lessons.forEach(l=>{const b=document.createElement('button');b.className='lessonItem'+(current?.id===l.id?' active':'');b.innerHTML=`<strong>${l.lesson_number}. ${l.title}</strong><br><span class="small">${l.mux_playback_id?'Video ready':'No video'}${l.is_published?' · Published':''}</span>`;b.onclick=()=>openLesson(l.id);host.appendChild(b)})}
function openLesson(id){current=lessons.find(x=>x.id===id);render();show('empty',false);show('editor',true);$('heading').textContent=`Lesson ${current.lesson_number}`;$('title').value=current.title||'';$('description').value=current.description||'';$('releaseAt').value=fmtLocal(current.release_at);$('videoState').textContent=current.mux_playback_id?`Video ready · ${current.duration_minutes||''} min`:'No video attached.';}
async function load(){try{const j=await api({action:'list-lessons'});lessons=j.lessons||[];show('loginCard',false);show('adminView',true);show('logout',true);render();if(lessons.length)openLesson(lessons[0].id)}catch(e){$('loginStatus').textContent=e.message;if(String(e.message).includes('Admin access'))$('loginStatus').textContent='This account is signed in but is not authorized as an ABBA Academy administrator.';}}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginStatus').textContent='Signing in...';const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginStatus').textContent=error.message;return}session=data.session;$('loginStatus').textContent='';await load()};
$('logout').onclick=async()=>{await db.auth.signOut();location.reload()};
$('saveMeta').onclick=async()=>{if(!current)return;try{$('saveMeta').disabled=true;await api({action:'update-lesson',lesson_id:current.id,title:$('title').value,description:$('description').value,release_at:$('releaseAt').value?new Date($('releaseAt').value).toISOString():null});const x=lessons.find(l=>l.id===current.id);x.title=$('title').value.trim();x.description=$('description').value.trim();x.release_at=$('releaseAt').value?new Date($('releaseAt').value).toISOString():null;render();$('saveMeta').textContent='Saved ✓';setTimeout(()=>$('saveMeta').textContent='Save lesson details',1500)}catch(e){alert(e.message)}finally{$('saveMeta').disabled=false}};
$('uploadBtn').onclick=async()=>{if(!current)return;const file=$('videoFile').files[0];if(!file){alert('Choose a video file first.');return}try{$('uploadBtn').disabled=true;show('progressWrap',true);$('uploadStatus').textContent='Preparing secure upload...';$('progressBar').style.width='2%';const j=await api({action:'create-upload',lesson_id:current.id});await uploadFile(j.upload_url,file);$('uploadStatus').textContent='Upload complete. Mux is processing the video...';$('progressBar').style.width='100%';await waitForAsset(j.upload_id,current.id)}catch(e){$('uploadStatus').textContent=e.message;$('uploadBtn').disabled=false}};
function uploadFile(url,file){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('PUT',url);x.upload.onprogress=e=>{if(e.lengthComputable){const p=Math.max(3,Math.round(e.loaded/e.total*90));$('progressBar').style.width=p+'%';$('uploadStatus').textContent=`Uploading ${p}%`;}};x.onload=()=>x.status>=200&&x.status<300?resolve():reject(new Error('Video upload failed.'));x.onerror=()=>reject(new Error('Network error during upload.'));x.send(file);});}
async function waitForAsset(uploadId,lessonId){for(let i=0;i<60;i++){await new Promise(r=>setTimeout(r,5000));try{const r=await fetch(`https://api.mux.com/video/v1/uploads/${uploadId}`);if(r.ok){const j=await r.json();const assetId=j.data?.asset_id;if(assetId){const s=await api({action:'sync-asset',lesson_id:lessonId,asset_id:assetId});if(s.ready){$('uploadStatus').textContent='Video ready and lesson published ✓';const item=lessons.find(l=>l.id===lessonId);item.mux_asset_id=assetId;item.mux_playback_id=s.playback_id;item.duration_minutes=s.duration_minutes;item.is_published=true;current=item;openLesson(lessonId);$('uploadBtn').disabled=false;return}}}}catch{} $('uploadStatus').textContent='Mux is processing the video...';} $('uploadStatus').textContent='Upload succeeded. Processing is taking longer than expected; refresh later.';$('uploadBtn').disabled=false;}
(async()=>{const {data:{session:s}}=await db.auth.getSession();if(s){session=s;await load()}})();