(()=>{
const T={
 en:{back:'← Back',signout:'Sign out',my:'My learning',continue:'Continue learning',up:'Up next',path:'Course path',modules:'Modules',lessons:'Lessons',enrollTitle:'Enrollment required',enrollCopy:'Your account is ready, but this course has not been activated for you yet.',enrollBtn:'View enrollment options',backCourse:'← Back to course',complete:'Mark lesson complete',completed:'Completed ✓',next:'Next lesson →',transcript:'Transcript',notes:'Notes',summary:'Summary',attachments:'Attachments',portal:'Student Portal',authCopy:'Sign in to continue your annual training program and keep your progress synchronized.',password:'Password',show:'Show',signin:'Sign in',create:'Create account',forgot:'Forgot password?',settings:'Settings',account:'ACCOUNT',studentAccount:'Student account',changePassword:'Change password',language:'LANGUAGE',preferred:'Preferred language',langHelp:'Choose the language used inside ABBA Academy. Your choice is saved to your account.',access:'COURSE ACCESS',active:'Active access',saveNote:'Save note',notePh:'Write your notes for this lesson...',key:'Key points',allLessons:'All available lessons completed',caught:'You are all caught up.',allCaught:'All caught up',none:'No more available lessons right now.',available:'available',module:'Module',lesson:'Lesson',of:'of',modulesCompleted:'modules completed',completedWord:'completed',start:'Start Lesson',resume:'Resume Lesson'},
 pt:{back:'← Voltar',signout:'Sair',my:'Meu aprendizado',continue:'Continuar aprendendo',up:'A seguir',path:'Caminho do curso',modules:'Módulos',lessons:'Aulas',enrollTitle:'Inscrição necessária',enrollCopy:'Sua conta está pronta, mas este curso ainda não foi ativado para você.',enrollBtn:'Ver opções de inscrição',backCourse:'← Voltar ao curso',complete:'Marcar como concluída',completed:'Concluída ✓',next:'Próxima aula →',transcript:'Transcrição',notes:'Notas',summary:'Resumo',attachments:'Materiais',portal:'Portal do Aluno',authCopy:'Entre para continuar seu programa anual e manter seu progresso sincronizado.',password:'Senha',show:'Mostrar',signin:'Entrar',create:'Criar conta',forgot:'Esqueceu a senha?',settings:'Configurações',account:'CONTA',studentAccount:'Conta do aluno',changePassword:'Alterar senha',language:'IDIOMA',preferred:'Idioma preferido',langHelp:'Escolha o idioma usado dentro da ABBA Academy. Sua escolha fica salva na sua conta.',access:'ACESSO AO CURSO',active:'Acesso ativo',saveNote:'Salvar nota',notePh:'Escreva suas notas desta aula...',key:'Pontos principais',allLessons:'Todas as aulas disponíveis foram concluídas',caught:'Você está em dia.',allCaught:'Tudo concluído',none:'Não há mais aulas disponíveis no momento.',available:'disponíveis',module:'Módulo',lesson:'Aula',of:'de',modulesCompleted:'módulos concluídos',completedWord:'concluídas',start:'Iniciar aula',resume:'Retomar aula'},
 es:{back:'← Volver',signout:'Cerrar sesión',my:'Mi aprendizaje',continue:'Continuar aprendiendo',up:'A continuación',path:'Ruta del curso',modules:'Módulos',lessons:'Clases',enrollTitle:'Inscripción requerida',enrollCopy:'Tu cuenta está lista, pero este curso todavía no ha sido activado para ti.',enrollBtn:'Ver opciones de inscripción',backCourse:'← Volver al curso',complete:'Marcar clase como completada',completed:'Completada ✓',next:'Siguiente clase →',transcript:'Transcripción',notes:'Notas',summary:'Resumen',attachments:'Materiales',portal:'Portal del estudiante',authCopy:'Inicia sesión para continuar tu programa anual y mantener tu progreso sincronizado.',password:'Contraseña',show:'Mostrar',signin:'Entrar',create:'Crear cuenta',forgot:'¿Olvidaste tu contraseña?',settings:'Configuración',account:'CUENTA',studentAccount:'Cuenta del estudiante',changePassword:'Cambiar contraseña',language:'IDIOMA',preferred:'Idioma preferido',langHelp:'Elige el idioma que se usa dentro de ABBA Academy. Tu elección se guarda en tu cuenta.',access:'ACCESO AL CURSO',active:'Acceso activo',saveNote:'Guardar nota',notePh:'Escribe tus notas de esta clase...',key:'Puntos clave',allLessons:'Todas las clases disponibles están completadas',caught:'Estás al día.',allCaught:'Todo al día',none:'No hay más clases disponibles por ahora.',available:'disponibles',module:'Módulo',lesson:'Clase',of:'de',modulesCompleted:'módulos completados',completedWord:'completadas',start:'Iniciar clase',resume:'Continuar clase'}
};
let lang='en',busy=false;
const q=id=>document.getElementById(id);
function txt(id,v){const e=q(id);if(e)e.textContent=v}
function apply(){if(busy)return;busy=true;const t=T[lang]||T.en;document.documentElement.lang=lang;
 txt('backHome',t.back);txt('signOutBtn',t.signout);txt('myLearningLabel',t.my);txt('continueLabel',t.continue);txt('upNextLabel',t.up);txt('coursePathLabel',t.path);txt('modulesTitle',t.modules);txt('lessonsTitle',t.lessons);txt('enrollmentTitle',t.enrollTitle);txt('enrollmentCopy',t.enrollCopy);txt('enrollmentBtn',t.enrollBtn);txt('backDashboardBtn',t.backCourse);txt('authTitle',t.portal);txt('authCopy',t.authCopy);txt('passwordLabel',t.password);txt('submitBtn',t.signin);txt('signUpBtn',t.create);txt('forgotBtn',t.forgot);txt('settingsTitle',t.settings);txt('accountLabel',t.account);txt('accountEmailTitle',t.studentAccount);txt('changePasswordLabel',t.changePassword);txt('languageLabel',t.language);txt('preferredLanguageLabel',t.preferred);txt('languageHelp',t.langHelp);txt('accessLabel',t.access);txt('courseAccessStatus',t.active);txt('settingsSignOutBtn',t.signout);txt('saveNoteBtn',t.saveNote);
 const note=q('lessonNote');if(note)note.placeholder=t.notePh;const tog=q('togglePassword');if(tog&&tog.textContent.trim()!=='Hide'&&tog.textContent.trim()!=='Ocultar')tog.textContent=t.show;
 document.querySelectorAll('.tab').forEach(b=>{const n=b.dataset.tab;if(n==='transcript')b.textContent=t.transcript;if(n==='notes')b.textContent=t.notes;if(n==='summary')b.textContent=t.summary;if(n==='attachments')b.textContent=t.attachments});
 const cb=q('completeBtn');if(cb)cb.textContent=cb.disabled?t.completed:t.complete;txt('nextBtn',t.next);
 const c=q('continueTitle');if(c){if(/All available lessons completed|Todas as aulas disponíveis|Todas las clases disponibles/.test(c.textContent))c.textContent=t.allLessons}
 const cm=q('continueMeta');if(cm){let m=cm.textContent.match(/(?:Start Lesson|Resume Lesson|Iniciar aula|Retomar aula|Iniciar clase|Continuar clase)\s*(\d+)/i);if(m)cm.textContent=(/Resume|Retomar|Continuar/.test(cm.textContent)?t.resume:t.start)+' '+m[1];else if(/caught up|em dia|al día/i.test(cm.textContent))cm.textContent=t.caught}
 const un=q('upNextTitle');if(un&&/All caught up|Tudo concluído|Todo al día/.test(un.textContent))un.textContent=t.allCaught;const um=q('upNextMeta');if(um&&/No more available|Não há mais|No hay más/.test(um.textContent))um.textContent=t.none;
 const pc=q('progressCount');if(pc){const m=pc.textContent.match(/(\d+)\s+(?:of|de)\s+(\d+)/i);if(m)pc.textContent=`${m[1]} ${t.of} ${m[2]} ${t.completedWord}`}
 const lt=q('lessonTotal');if(lt){const m=lt.textContent.match(/(\d+)/);if(m)lt.textContent=`${m[1]} ${t.available}`}
 const ms=q('moduleSummary');if(ms){const m=ms.textContent.match(/(\d+)\s+(?:of|de)\s+(\d+)/i);if(m)ms.textContent=`${m[1]} ${t.of} ${m[2]} ${t.modulesCompleted}`}
 document.querySelectorAll('.module-card').forEach(card=>{card.querySelectorAll('small,strong').forEach(e=>{e.textContent=e.textContent.replace(/^Module\s+(\d+)/i,`${t.module} $1`).replace(/^Módulo\s+(\d+)/i,`${t.module} $1`).replace(/^Lessons\s+/i,t.lessons+' ').replace(/^Aulas\s+/i,t.lessons+' ').replace(/(\d+)\s+of\s+(\d+)\s+completed/i,`$1 ${t.of} $2 ${t.completedWord}`).replace(/(\d+)\s+de\s+(\d+)\s+(concluídas|completadas)/i,`$1 ${t.of} $2 ${t.completedWord}`)})});
 document.querySelectorAll('.lesson-btn small').forEach(e=>{if(/Completed|Conclu|Completad/i.test(e.textContent))e.textContent=t.completedWord.charAt(0).toUpperCase()+t.completedWord.slice(1)});
 document.querySelectorAll('#summaryContent h4').forEach(e=>e.textContent=t.key);
 busy=false;}
async function loadPref(){const {data:{session}}=await db.auth.getSession();if(!session){lang='en';apply();return}q('settingsBtn')?.classList.remove('hidden');q('settingsEmail').textContent=session.user.email||'';const {data}=await db.from('abba_student_settings').select('preferred_language').eq('user_id',session.user.id).maybeSingle();lang=['en','pt','es'].includes(data?.preferred_language)?data.preferred_language:'en';q('languageSelect').value=lang;apply()}
function openSettings(){q('settingsPanel')?.classList.remove('hidden');q('languageSelect').value=lang;apply()}
function closeSettings(){q('settingsPanel')?.classList.add('hidden')}
q('settingsBtn')?.addEventListener('click',openSettings);q('closeSettingsBtn')?.addEventListener('click',closeSettings);q('settingsPanel')?.addEventListener('click',e=>{if(e.target===q('settingsPanel'))closeSettings()});
q('languageSelect')?.addEventListener('change',async e=>{const v=e.target.value;if(!['en','pt','es'].includes(v))return;lang=v;apply();const {data:{session}}=await db.auth.getSession();if(!session)return;const {error}=await db.from('abba_student_settings').upsert({user_id:session.user.id,preferred_language:v,updated_at:new Date().toISOString()},{onConflict:'user_id'});txt('settingsStatus',error?'Could not save language.':(v==='pt'?'Idioma salvo ✓':v==='es'?'Idioma guardado ✓':'Language saved ✓'))});
q('resetPasswordBtn')?.addEventListener('click',async()=>{const {data:{session}}=await db.auth.getSession();if(!session?.user?.email)return;const {error}=await db.auth.resetPasswordForEmail(session.user.email,{redirectTo:'https://alineramiro.com/academy-reset.html'});txt('settingsStatus',error?error.message:(lang==='pt'?'Enviamos um link para alterar sua senha.':lang==='es'?'Te enviamos un enlace para cambiar tu contraseña.':'We sent you a password reset link.'))});
q('settingsSignOutBtn')?.addEventListener('click',async()=>{await db.auth.signOut();location.reload()});
new MutationObserver(()=>{clearTimeout(window.__abbaI18n);window.__abbaI18n=setTimeout(apply,30)}).observe(document.body,{subtree:true,childList:true,characterData:true});
loadPref();
})();