(function(){
'use strict';
var BASE='https://yecywtxbuhfukergbwfc.supabase.co';
var KEY='sb_publishable_jFIuvZYIs1b-6IjqCnDPDw_BDivhFKs';
var ADMIN='alineramirocontact@gmail.com';
var token=localStorage.getItem('aline_admin_token')||'';
function el(id){return document.getElementById(id);}
function status(id,text,bad){var x=el(id);if(!x)return;x.textContent=text;x.style.display='block';x.style.background=bad?'#fff0ee':'#eef5ff';}
async function call(path,method,body,extra){var headers={apikey:KEY};if(token)headers.Authorization='Bearer '+token;if(extra){for(var k in extra)headers[k]=extra[k];}var options={method:method||'GET',headers:headers};if(body!==undefined&&body!==null){headers['Content-Type']='application/json';options.body=JSON.stringify(body);}var r=await fetch(BASE+path,options);var txt=await r.text();var data=null;try{data=txt?JSON.parse(txt):null;}catch(e){data=txt;}if(!r.ok){var m=(data&&((data.msg)||(data.message)||(data.error_description)||(data.error)))||('Erro '+r.status);throw new Error(m);}return data;}
async function signUp(){var p=el('password').value||'';if(p.length<8){status('authStatus','Crie uma senha com pelo menos 8 caracteres.',true);return;}status('authStatus','Criando acesso...',false);try{await call('/auth/v1/signup','POST',{email:ADMIN,password:p,data:{site:'alineramiro'}});status('authStatus','Conta criada. Verifique o e-mail de Aline para confirmar. Depois volte e pressione Entrar.',false);}catch(e){status('authStatus',e.message,true);}}
async function signIn(){var p=el('password').value||'';if(!p){status('authStatus','Digite sua senha.',true);return;}status('authStatus','Entrando...',false);try{var d=await call('/auth/v1/token?grant_type=password','POST',{email:ADMIN,password:p});token=d.access_token;localStorage.setItem('aline_admin_token',token);showApp();await loadAll();}catch(e){status('authStatus',e.message,true);}}
function showApp(){el('loginBox').style.display='none';el('app').style.display='block';el('logout').style.display='inline-block';}
function showLogin(){el('loginBox').style.display='block';el('app').style.display='none';el('logout').style.display='none';}
async function getRows(table,order){var p='/rest/v1/'+table+'?select=*';if(order)p+='&order='+encodeURIComponent(order);return call(p,'GET',null,{Accept:'application/json'});}
async function insertRow(table,obj){return call('/rest/v1/'+table,'POST',obj,{Prefer:'return=minimal'});}
async function upsertContent(obj){return call('/rest/v1/aline_site_content?on_conflict=content_key','POST',obj,{Prefer:'resolution=merge-duplicates,return=minimal'});}
async function deleteRow(table,id){return call('/rest/v1/'+table+'?id=eq.'+encodeURIComponent(id),'DELETE',null,{Prefer:'return=minimal'});}
async function upload(file,folder){if(!file)return null;var safe=file.name.toLowerCase().replace(/[^a-z0-9.]+/g,'-');var path=folder+'/'+Date.now()+'-'+safe;var r=await fetch(BASE+'/storage/v1/object/aline-public/'+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});if(!r.ok){var t=await r.text();throw new Error(t||'No se pudo subir el archivo');}return BASE+'/storage/v1/object/public/aline-public/'+path;}
function clear(node){while(node.firstChild)node.removeChild(node.firstChild);}
function listItem(image,title,sub,table,id){var row=document.createElement('div');row.className='item';if(image){var img=document.createElement('img');img.src=image;img.alt='';row.appendChild(img);}else{row.appendChild(document.createElement('div'));}var text=document.createElement('div');var strong=document.createElement('strong');strong.textContent=title||'';text.appendChild(strong);var small=document.createElement('div');small.className='small';small.textContent=sub||'';text.appendChild(small);row.appendChild(text);var b=document.createElement('button');b.className='btn danger';b.type='button';b.textContent='Excluir';b.onclick=async function(){if(!confirm('Excluir este item?'))return;try{await deleteRow(table,id);await loadAll();}catch(e){alert(e.message);}};row.appendChild(b);return row;}
async function loadContent(){try{var data=await getRows('aline_site_content');for(var i=0;i<data.length;i++){var x=el(data[i].content_key);if(x)x.value=String(data[i].content_value||'').replace(/\\\\n/g,'\n');}}catch(e){status('contentStatus',e.message,true);}}
async function saveContent(){var keys=['hero_roles_pt','bio_pt','training_title_pt','training_body_pt','training_cta_pt','training_contact_pt','contact_email'];status('contentStatus','Salvando...',false);try{for(var i=0;i<keys.length;i++){await upsertContent({content_key:keys[i],content_value:el(keys[i]).value,updated_at:new Date().toISOString()});}status('contentStatus','Conteúdo salvo com sucesso.',false);}catch(e){status('contentStatus',e.message,true);}}
async function loadMedia(){try{var d=await getRows('aline_media','created_at.desc');var box=el('mediaList');clear(box);for(var i=0;i<d.length;i++)box.appendChild(listItem(d[i].file_url,d[i].title||'Foto',d[i].placement||'', 'aline_media',d[i].id));}catch(e){}}
async function addMedia(){var f=el('mediaFile').files[0];if(!f){status('mediaStatus','Selecione uma foto.',true);return;}status('mediaStatus','Enviando...',false);try{var u=await upload(f,'photos');await insertRow('aline_media',{media_type:'image',title:el('mediaTitle').value,file_url:u,alt_text:el('mediaAlt').value,placement:el('mediaPlacement').value,is_published:true,sort_order:Date.now()});el('mediaFile').value='';el('mediaTitle').value='';el('mediaAlt').value='';status('mediaStatus','Foto publicada.',false);await loadMedia();}catch(e){status('mediaStatus',e.message,true);}}
async function loadBooks(){try{var d=await getRows('aline_books','sort_order.asc');var box=el('bookList');clear(box);for(var i=0;i<d.length;i++)box.appendChild(listItem(d[i].cover_url,d[i].title,d[i].subtitle||'','aline_books',d[i].id));}catch(e){}}
async function addBook(){if(!el('bookTitle').value){status('bookStatus','Digite o título.',true);return;}status('bookStatus','Salvando...',false);try{var cover=await upload(el('bookFile').files[0],'books');await insertRow('aline_books',{title:el('bookTitle').value,subtitle:el('bookSubtitle').value,description:el('bookDescription').value,cover_url:cover,purchase_url:el('bookUrl').value,is_published:true,sort_order:Date.now()});status('bookStatus','Livro adicionado.',false);await loadBooks();}catch(e){status('bookStatus',e.message,true);}}
async function loadProducts(){try{var d=await getRows('aline_products','sort_order.asc');var box=el('productList');clear(box);for(var i=0;i<d.length;i++)box.appendChild(listItem(d[i].image_url,d[i].name,d[i].price_label||'','aline_products',d[i].id));}catch(e){}}
async function addProduct(){if(!el('productName').value){status('productStatus','Digite o nome.',true);return;}status('productStatus','Salvando...',false);try{var image=await upload(el('productFile').files[0],'products');await insertRow('aline_products',{name:el('productName').value,description:el('productDescription').value,image_url:image,purchase_url:el('productUrl').value,price_label:el('productPrice').value,is_published:true,sort_order:Date.now()});status('productStatus','Produto adicionado.',false);await loadProducts();}catch(e){status('productStatus',e.message,true);}}
async function loadAll(){await Promise.all([loadContent(),loadMedia(),loadBooks(),loadProducts()]);}
function tabs(){var ts=document.querySelectorAll('.tab');for(var i=0;i<ts.length;i++){ts[i].onclick=function(){var a=document.querySelectorAll('.tab');var s=document.querySelectorAll('.section');for(var j=0;j<a.length;j++)a[j].classList.remove('active');for(var k=0;k<s.length;k++)s[k].classList.remove('active');this.classList.add('active');el(this.getAttribute('data-section')).classList.add('active');};}}
async function init(){el('signUp').onclick=signUp;el('signIn').onclick=signIn;el('logout').onclick=function(){token='';localStorage.removeItem('aline_admin_token');showLogin();};el('saveContent').onclick=saveContent;el('uploadMedia').onclick=addMedia;el('addBook').onclick=addBook;el('addProduct').onclick=addProduct;tabs();if(!token){showLogin();return;}try{var u=await call('/auth/v1/user','GET');if((u.email||'').toLowerCase()===ADMIN){showApp();await loadAll();}else{throw new Error('not-admin');}}catch(e){token='';localStorage.removeItem('aline_admin_token');showLogin();}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();